spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # 用户权限认证
        - id: user_oauth
          uri: lb://user-oauth
          predicates:
            - Path=/oauth/**
        # 用户服务
        - id: user_service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        # 秒杀服务
        - id: seckill_service
          uri: lb://seckill
          predicates:
            - Path=/seckillgoods/**,/seckillorder/**,/webSocket/**,/alipay/**
    nacos:
      discovery:
        server-addr: 42.194.147.155:8848
  redis:
    host: 42.194.147.155
server:
  port: 80
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true
