server:
  port: 9005
spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/pinyougoudb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: root
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  redis:
    host: 42.194.147.155
  rabbitmq:
    host: 127.0.0.1
  cloud:
    nacos:
      discovery:
        server-addr: 42.194.147.155:8848
mybatis:
  type-aliases-package: com.bnz.miaosha.user.pojo
  mapper-locations: classpath:mapper/*.xml
#feign:
#  hystrix:
#    enabled: true
#  client:
#    config:
#      default:   #配置全局的feign的调用超时时间  如果 有指定的服务配置 默认的配置不会生效
#        connectTimeout: 60000 # 指定的是 消费者 连接服务提供者的连接超时时间 是否能连接  单位是毫秒
#        readTimeout: 20000  # 指定的是调用服务提供者的 服务 的超时时间（）  单位是毫秒
#hystrix 配置
#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          #如果enabled设置为false，则请求超时交给ribbon控制
#          enabled: true
#        isolation:
#          strategy: SEMAPHORE
#          thread:
#            # 熔断器超时时间，默认：1000/毫秒
#            timeoutInMilliseconds: 20000
feign:
  httpclient:
    enabled: true

